### ISSUE TITLE
BH1750_SetMtreg not working

### ISSUE THREAD

**Issue by stm32f4** [lamik/Light_Sensors_STM32#1]
Hello,

The function does not work due to improper i2c sequence. The datasheet requests that each command is followed by a stop sequence.
Page 10 of 2011.11 rev D datasheet :

> BH1750FVI is not able to accept plural command without stop condition. Please insert SP every 1 Opecode

The current code sends two bytes in a row. I made a small change in my lmocal copy and it works.
Otherwise great Job !

**Comment by lamik** [comment]
Thanks man! Could you provide me your changes? I will check it and apply it to my repo.

**Comment by lamik** [comment]
Thank you for patch!
